minimum_pre_commit_version: 2.11.0
default_language_version:
  python: python3

exclude: ^(src/board.py|src/piece_square_tables.py|tests/*|src/hueristic.py|__init__.py|src/__init__.py)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=1800]
      - id: check-json
      # - id: debug-statements
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [-l, "120", --skip-string-normalization]
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, "--ignore=E203,W503"]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--profile, black, --line-length, "120", --filter-files]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v0.991
  #   hooks:
  #     - id: mypy
  #       args: [--no-namespace-packages]
  #       additional_dependencies: [types-requests, types-PyYaml, types-aiofiles]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.1
